# Generated by Django 3.1.7 on 2021-04-20 10:00

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0005_auto_20210412_1948'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, help_text='You may keep it blank', max_length=200)),
                ('company_name', models.CharField(max_length=200)),
                ('starting_date', models.DateField(blank=True, null=True)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('salary', models.PositiveIntegerField()),
                ('vacancy', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)])),
                ('job_category', models.CharField(choices=[('swe', 'Software Engineering'), ('wdd', 'Web Design & Development'), ('dsa', 'Data Science & Analytics'), ('gd', 'Graphic Design'), ('sqa', 'Software Quality Assurance'), ('nsa', 'Network & System Admin'), ('it', 'Information Technology'), ('cce', 'Cloud Computing & Engineering'), ('cc', 'Cyber Security')], max_length=3)),
                ('job_type', models.CharField(choices=[('ft', 'Full Time'), ('pt', 'Part Time'), ('ip', 'Internship'), ('re', 'Remote'), ('ct', 'Contractual')], max_length=2)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=11, null=True)),
                ('company_website', models.URLField()),
                ('logo', models.ImageField(blank=True, null=True, upload_to='')),
                ('address', models.TextField(max_length=200)),
                ('division', models.CharField(choices=[('dhk', 'Dhaka'), ('ctg', 'Chittagong'), ('rjs', 'Rajshahi'), ('khl', 'Khulna'), ('bar', 'Barishal'), ('syl', 'Sylhet'), ('rng', 'Rangpur')], max_length=4)),
                ('description', models.TextField()),
                ('responsibility', models.TextField()),
                ('min_education', models.CharField(choices=[('postgraduate', 'Post Graduate'), ('graduate', 'Graduate'), ('hsc', 'HSC'), ('ssc', 'SSC'), ('noneed', "Doesn't Matter")], max_length=12)),
                ('cgpa', models.DecimalField(decimal_places=2, max_digits=3)),
                ('experience', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(15)])),
                ('skill_req', models.TextField(help_text='Input skills with comma')),
                ('skill_bonus', models.CharField(help_text='Input skills with comma', max_length=255)),
                ('status', models.CharField(choices=[('publish', 'Publish'), ('hide', 'Hide')], max_length=10)),
                ('publish', models.DateField(auto_now_add=True)),
                ('last_modified', models.DateField(auto_now=True)),
                ('applicant', models.ManyToManyField(related_name='jobs', to='account.Applicant')),
                ('recruiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='account.recruiter')),
            ],
        ),
    ]
