# Generated by Django 3.1.7 on 2021-04-20 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20210412_1948'),
        ('cvrecommender', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='applicant',
            field=models.ManyToManyField(blank=True, null=True, related_name='jobs', to='account.Applicant'),
        ),
    ]
