# Generated by Django 3.1.7 on 2021-04-22 14:14

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('cvrecommender', '0003_auto_20210422_1419'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='job',
            managers=[
                ('published', django.db.models.manager.Manager()),
            ],
        ),
    ]
