# Generated by Django 3.1.7 on 2021-04-29 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvrecommender', '0005_auto_20210423_2249'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='job',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='job',
            name='division',
            field=models.CharField(choices=[('Dhaka', 'Dhaka'), ('Chittagong', 'Chittagong'), ('Rajshahi', 'Rajshahi'), ('Khulna', 'Khulna'), ('Barishal', 'Barishal'), ('Sylhet', 'Sylhet'), ('Rangpur', 'Rangpur')], max_length=15),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_category',
            field=models.CharField(choices=[('Software Engineering', 'Software Engineering'), ('Web Design and Development', 'Web Design & Development'), ('Data Science and Analytics', 'Data Science & Analytics'), ('Graphic Design', 'Graphic Design'), ('Software Quality Assurance', 'Software Quality Assurance'), ('Network and System Admin', 'Network & System Admin'), ('Information Technology', 'Information Technology'), ('Cloud Computing and Engineering', 'Cloud Computing & Engineering'), ('Cyber Security', 'Cyber Security')], max_length=50),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('Full Time', 'Full Time'), ('Part Time', 'Part Time'), ('Internship', 'Internship'), ('Remote', 'Remote'), ('Contractual', 'Contractual')], max_length=20),
        ),
        migrations.AlterField(
            model_name='job',
            name='min_education',
            field=models.CharField(choices=[('Post Graduate', 'Post Graduate'), ('Graduate', 'Graduate'), ('HSC', 'HSC'), ('SSC', 'SSC')], max_length=20),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('Published', 'Published'), ('Hidden', 'Hidden')], max_length=20),
        ),
    ]
