# Generated by Django 3.1.7 on 2021-05-02 16:39

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20210412_1948'),
        ('cvrecommender', '0006_auto_20210429_2204'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=20)),
                ('age', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(60)])),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=11)),
                ('education_application', models.CharField(choices=[('Post Graduate', 'Post Graduate'), ('Graduate', 'Graduate'), ('HSC', 'HSC'), ('SSC', 'SSC')], max_length=20)),
                ('cgpa_application', models.DecimalField(decimal_places=2, max_digits=3)),
                ('skill_req_application', models.TextField()),
                ('skill_bonus_application', models.CharField(blank=True, max_length=255, null=True)),
                ('related_experience_application', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(15)])),
                ('total_experience_application', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(15)])),
                ('note_application', models.TextField()),
                ('cv_application', models.FileField(upload_to='')),
                ('applicant', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobApplications', to='account.applicant')),
            ],
        ),
    ]
