# Generated by Django 3.1.7 on 2021-05-02 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cvrecommender', '0007_jobapplication'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplication',
            name='age',
        ),
    ]
