# Generated by Django 3.1.7 on 2021-05-02 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvrecommender', '0008_remove_jobapplication_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='note_application',
            field=models.TextField(blank=True, null=True),
        ),
    ]
