# Generated by Django 3.1.7 on 2021-04-11 13:57

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recruiter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.IntegerField(validators=[django.core.validators.RegexValidator(code='Bangladeshi phone number without country code', message='Bangladeshi phone number without country code', regex='^01[13-9]\\d{8}$')])),
                ('organization', models.CharField(max_length=100)),
                ('details', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='users/%Y/%m/%d/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.IntegerField(validators=[django.core.validators.RegexValidator(code='Bangladeshi phone number without country code', message='Bangladeshi phone number without country code', regex='^01[13-9]\\d{8}$')])),
                ('work_exp', models.CharField(blank=True, max_length=50, null=True)),
                ('summary', models.TextField(max_length=255)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default='Male', max_length=10)),
                ('address', models.TextField(max_length=100)),
                ('dob', models.DateField(blank=True, null=True)),
                ('language', models.CharField(max_length=100)),
                ('website', models.URLField()),
                ('image', models.ImageField(blank=True, upload_to='users/%Y/%m/%d/')),
                ('category', models.CharField(choices=[('webdeveloper', 'Web Developer'), ('softwareengineer', 'Software Engineer'), ('mobileapplication', 'Mobile Application')], default='Web Developer', max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
