# Generated by Django 3.1.7 on 2021-04-11 14:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='phone',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.RegexValidator(code='Bangladeshi phone number without country code', message='Bangladeshi phone number without country code', regex='^01[13-9]\\d{8}$')]),
        ),
        migrations.AlterField(
            model_name='recruiter',
            name='phone',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.RegexValidator(code='Bangladeshi phone number without country code', message='Bangladeshi phone number without country code', regex='^01[13-9]\\d{8}$')]),
        ),
    ]
