# Generated by Django 3.1.7 on 2021-04-11 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20210411_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='phone',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recruiter',
            name='phone',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
