# Generated by Django 3.1.7 on 2021-04-11 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20210411_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='phone',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='recruiter',
            name='phone',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
